import { Brand } from './schema';

/**
 * Brands taxonomy data
 * Contains all scooter manufacturers, OEM parts suppliers, and accessory brands
 */
export const brands: Brand[] = [
  {
    id: 'tiger',
    slug: 'tiger',
    name: 'Tiger',
    nameUk: 'Tiger',
    logo: null,
    website: 'https://hiley.com.ua',
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'nami',
    slug: 'nami',
    name: 'Nami',
    nameUk: 'Nami',
    logo: null,
    website: null,
    country: 'South Korea',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'kaabo',
    slug: 'kaabo',
    name: 'Kaabo',
    nameUk: 'Kaabo',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'teverun',
    slug: 'teverun',
    name: 'Teverun',
    nameUk: 'Teverun',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'inmotion',
    slug: 'inmotion',
    name: 'Inmotion',
    nameUk: 'Inmotion',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'mars',
    slug: 'mars',
    name: 'Mars / Teewing',
    nameUk: 'Mars / Teewing',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'surron',
    slug: 'surron',
    name: 'Surron',
    nameUk: 'Surron',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'nanrobot',
    slug: 'nanrobot',
    name: 'Nanrobot',
    nameUk: 'Nanrobot',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'kwheel',
    slug: 'kwheel',
    name: 'KWHEEL',
    nameUk: 'KWHEEL',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'bucklos',
    slug: 'bucklos',
    name: 'BUCKLOS',
    nameUk: 'BUCKLOS',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'rockbros',
    slug: 'rockbros',
    name: 'ROCKBROS',
    nameUk: 'ROCKBROS',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'toptrek',
    slug: 'toptrek',
    name: 'Toptrek',
    nameUk: 'Toptrek',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'macury',
    slug: 'macury',
    name: 'MACURY',
    nameUk: 'MACURY',
    logo: null,
    website: null,
    country: 'China',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'scootify',
    slug: 'scootify',
    name: 'Scootify',
    nameUk: 'Scootify',
    logo: null,
    website: null,
    country: 'Ukraine',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

/**
 * Get a brand by its ID
 * @param id - The brand ID to look up
 * @returns The brand object or undefined if not found
 */
export function getBrandById(id: string): Brand | undefined {
  return brands.find(b => b.id === id);
}
